### ISSUE TITLE
Provide a Global Cache for popular Frameworks

### ISSUE THREAD

**Issue by Jeehut** [JamitLabs/Accio#14]
While there's already a local and a shared cache option available, both of these are not particularly useful when installing dependencies (the first time) on a CI. CI build times can be very long (especially on first run) for dependencies. While some might opt to configure their shared cache on the CI as well, this can be a hassle dependending on the service used for the shared cache.

A global cache could be tackled in various ways:

1. Everybody using Accio worldwide could opt to upload any build products to the global cache. Advantages: High availability of frameworks. Disadvantages: Security concerns and too much space taken by build products.
2. Only GitHub Open Source frameworks with at least 100 stars and only versioned releases could be uploaded by everyone using Accio to the global cache. Advantages: Relatively high availability of frameworks & managable space taken by build products. Disadvantages: Security concerns.
3. A CI/Backend is provided specifically for building products and each instance of Accio can ask it to build a specific Open Source project – only versioned releases and at least 100 stars needed so it's actuallly built. Advantages: Better security (depending on CI/backend), relatively high availability of frameworks & managable space taken. Disadvantages: Framework availability delayed, costs for CI/backend.

These are the ways I think this could be tackled. I personally prefer point 3 most since [XcodeGhost](https://en.wikipedia.org/wiki/XcodeGhost) could always happen again and I don't want to be responsible for malware. I'm also very open to other ideas from the community – this will probably not be tackled until I feel we have found the best possible way dealing with a global cache. 

Although I have only CI builds as a use case this feature was mainly designed for, I'm pretty sure that if we provide this feature, some developers will always use it regardless of any security concerns of warnings we might mention in the README.

**Comment by fredpi** [comment]
Closing this, as [Accio is now deprecated](https://github.com/JamitLabs/Accio/pull/92).
