### ISSUE TITLE
Add command to test support of frameworks

### ISSUE THREAD

**Issue by Jeehut** [JamitLabs/Accio#16]
Some frameworks might want to test their Accio support on a CI. As of now, there is no command to test if a framework itself is Accio compatible, the only solution is a workaround where one would need to create a Package.swift file which includes the framework to be tested. This is no good solution for a CI, therefore Accio should provide an internal way of testing Accio installation of a framework.

Note though, that in practice a framework that supports SwiftPM _and_ Carthage will always also support Accio. But projects bundling resources can't have _real_ SwiftPM support at the moment, therefore adding a command for testing Accio support definitely is needed for those projects.

**Comment by mrylmz** [comment]
I would suggest to add a new `accio doctor` command which scans the current project directory for possible issues like missing support and outputs helpful informations on how to solve the issue or suggest a auto-fixit if possible.

**Comment by Jeehut** [comment]
@mrylmz Great idea! But please open a new issue for that and list the different errors you would want to help out with initially. It should be developed separately from this.

**Comment by Jeehut** [comment]
As for the naming of this feature, I suggest the following:
- `accio supports ios` to check if the current framework supports building for iOS
- `accio supports ios,tvos` to check if the current framework supports building for iOS & tvOS
- `accio supports` which does exactly the same like `accio supports iOS,tvOS,macOS,watchOS`

**Comment by Jeehut** [comment]
@mrylmz Any progress on this issue? Feel free to create a [WIP] PR if you're not finished yet so I could continue on your work if needed.

**Comment by Jeehut** [comment]
@mrylmz ping :)

**Comment by mrylmz** [comment]
Its been a while since my last progress now... feel free to continue the work on the branch `work/16-support-command`

**Comment by fredpi** [comment]
Closing this, as [Accio is now deprecated](https://github.com/JamitLabs/Accio/pull/92).
