### ISSUE TITLE
Drop Carthage requirement by replicating the `build` command

### ISSUE THREAD

**Issue by Jeehut** [JamitLabs/Accio#18]
As a consequence of #17 it could make sense to integrate the used parts of Carthage right into Accio to prevent having Carthage as a dependency. This could also fix any issues that might arise in the future due to any changes in Carthage or people using Accio with an old version of Carthage. Also, we could fix any issues within the build command faster than Carthage does if such a situation arises.

**Comment by fredpi** [comment]
Closing this, as [Accio is now deprecated](https://github.com/JamitLabs/Accio/pull/92).
