### ISSUE TITLE
dyld: Symbol not found: _$s11ReactiveKit7NoErrorON

### ISSUE THREAD

**Issue by Jeehut** [JamitLabs/Accio#21]
For some frameworks with subdependencies like Bond, when running the app in the Demo project, the simulator fails with the following error:

```
dyld: Symbol not found: _$s11ReactiveKit7NoErrorON
  Referenced from: /Users/Me/Library/Developer/CoreSimulator/Devices/4238123B-BA44-4806-A8CC-A24998F275BA/data/Containers/Bundle/Application/8B87D39E-79A6-43BD-810D-70A2EA4AA6BC/Demo-iOS.app/Frameworks/Bond.framework/Bond
  Expected in: /Users/Me/Library/Developer/CoreSimulator/Devices/4238123B-BA44-4806-A8CC-A24998F275BA/data/Containers/Bundle/Application/8B87D39E-79A6-43BD-810D-70A2EA4AA6BC/Demo-iOS.app/Frameworks/ReactiveKit.framework/ReactiveKit
 in /Users/Me/Library/Developer/CoreSimulator/Devices/4238123B-BA44-4806-A8CC-A24998F275BA/data/Containers/Bundle/Application/8B87D39E-79A6-43BD-810D-70A2EA4AA6BC/Demo-iOS.app/Frameworks/Bond.framework/Bond
```

This also happens when Moya and a different version of Alamofire are specified with Moya stating that it couldn't find Alamofire. The supposedly missing frameworks are actually existent though. So this might only be a linking issue within the frameworks using them as subdependency. The weird part though is that building works, which shouldn't be possible if the required frameworks are missing ... this needs further investigation and tests.

**Comment by srdanrasic** [comment]
`NoError` has been deprecated recently since ReactiveKit 3.10. I’ve seen something similar once when a framework would be built against version A of another framework and then linked with version B of the same framework.

**Comment by Jeehut** [comment]
Sorry, I'm not sure if I understand this, I'm understanding the following, correct me if I'm wrong:

1. ReactiveKit won't have `NoError` in future releases, so pointing to the `master` branch might fix this
2. Check if ReactiveKit is linked directly and as a dependency with different versions, that might fix it

Please note that currently ReactiveKit is only linked in one place, being as a dependency to `Bond`. I'm not directly linking it anywhere and also couldn't find it as a subdependency elsewhere.

**Comment by srdanrasic** [comment]
In v3.9 and earlier, we had `enum NoError {}`. Now in v3.10 that's replaced with `@deprecated typealias NoError = Swift.Never`. So, nothing is broken and pointing to another branch won't fix the issue you have. 

I just wanted to give you a possible direction to look at while trying to figure out the problem which is contained in the second sentence:
> I’ve seen something similar once when a framework would be built against version A of another framework and then linked with version B of the same framework.

**Comment by Jeehut** [comment]
I investigated this and it turned out that the issue was that Bond had linked its subdependencies via submodules with depending projects. See my comment [here](https://github.com/DeclarativeHub/Bond/pull/621#issuecomment-482128433) for further details (including the fix).

In any case this isn't a bug within Accio. How this could be prevented in the future – if at all possible – isn't clear to me. If someone has an idea, feel free to ping me, but in the meantime I'll mark this "won't fix".
