### ISSUE TITLE
Error reverting changes in the checkouts directory

### ISSUE THREAD

**Issue by fredpi** [JamitLabs/Accio#27]
In my current configuration (with only 1 package), I somehow managed to break the `✨  Reverting any changes in the checkouts directory ...` step. The following problem occurs: `An error occurred: Command '/bin/bash -c "git -C '/[MyProjectPath]/.accio/checkouts/PMJSON' reset HEAD --hard --quiet 2> /dev/null"' returned with error code 128.`

When I copy this repo to another folder and run the failing command (`git -C '[NewPath]/PMJSON' reset HEAD --hard`) manually, there's still an error: `fatal: Could not parse object 'HEAD'.`

Maybe this problem is related to the fact that after initializing accio and then switching to a branch where it wasn't installed yet, I performed a `Reset All` of the original repo via Sourcetree to reset the `.accio` folder. Maybe this had an effect on the recursive subrepos (those within `.accio/checkouts`), so that after switching to the accio branch again, running `accio install` failed. Still weird, that the checkouts folder survived the git reset... 🤔

**Comment by Jeehut** [comment]
I saw this issue once, too in an app project. So it's definitely happening often enough, that I will have a detailed look once I come across it again. Unfortunately I didn't have much time when it happened to I worked around it by running `accio clean` once and `accio update` after that. Then everything worked without issues.

I will also checkout your example ZIP file and try to reproduce this once I have time. Thank you for reporting this and the detailed description.
