### ISSUE TITLE
Linking problems with apps split into modules

### ISSUE THREAD

**Issue by Jeehut** [JamitLabs/Accio#29]
When an app has multiple targets with the same platform, e.g. an „App“ target an an „AppKit“ target and both include the same framework, then Accio currently adds only a single framework to the group properly. It seems to try to add a second link, too, but fails - Xcode is placing the second under „Reconstructed Links“ (or similar).

A workaround is to link the frameworks manually, Accio correctly handles them on updates from then on. But Accio should link them correctly in the first place.

**Comment by mrylmz** [comment]
Are the targets using the same version of the Dependency? 

If both are requiring the same Dependency and you link that dependency with your target once then there shouldn't be any issues building. 

Could you please provide further informations like logs.

**Comment by Jeehut** [comment]
@mrylmz I think you didn‘t quite understand the issue. Just add a second iOS target to the demo project and link Moya against both, then run accio update. You‘ll see what I mean then.

**Comment by Jeehut** [comment]
@mrylmz See also https://github.com/JamitLabs/Accio/issues/28, where you can find an example package manifest.
