### ISSUE TITLE
Framework targets have Carthage copy script

### ISSUE THREAD

**Issue by Jeehut** [JamitLabs/Accio#30]
I‘m not sure if this is a problem at all, but currently when an app has the targets, say „App“ and „AppKit“ where AppKit is a framework used within the app, then the Carthage copy build script is added to the framework target, too.

This might be correct behavior after all, but I feel like I already ran into double linking problems during App store upload in such cases. This should be double checked and fixed if necessary.

**Comment by fredpi** [comment]
Closing this, as [Accio is now deprecated](https://github.com/JamitLabs/Accio/pull/92).
