### ISSUE TITLE
Test Coverage: Migrate some open source Apps to Accio

### ISSUE THREAD

**Issue by Jeehut** [JamitLabs/Accio#31]
Currently, only a few project structures and sets of dependencies are tested with Accio. While most should be usable as is, it would make sense to migrate several open source iOS apps from Carthage to Accio to find edge cases (or confirm there are none). [Here](https://github.com/dkhamsing/open-source-ios-apps)'s a repo with many such projects. 

Bigger and wider known app projects could be started with, like [Firefox](https://github.com/mozilla-mobile/firefox-ios).

**Comment by fredpi** [comment]
Closing this, as [Accio is now deprecated](https://github.com/JamitLabs/Accio/pull/92).
