### ISSUE TITLE
New Option: Use SwiftPM for building when possible

### ISSUE THREAD

**Issue by Jeehut** [JamitLabs/Accio#32]
Currently this projects uses Carthage for building frameworks. While this especiallly is a great solution for frameworks specifically written for iOS etc. (#18 being an improvement which drops the Carthage requirement), some libraries were written for SwiftPM usage only and might not integrate well with the current approach in Accio.

For example, when I tried adding [NIOTransportServices](https://github.com/apple/swift-nio-transport-services) to an iOS application, it build all just fine with Accio but then when running the app, I got linker errors and the app crashed.

Maybe the approach described in [this article](https://badootech.badoo.com/swift-package-manager-builds-ios-frameworks-updated-xcode-10-2-beta-19b3e6741bda) or used by [this tool](https://gitlab.com/Pyroh/xspm) might work better in such cases. 

Therefore investigating other approaches of building and integrating frameworks could bring Accio another step forward. This doesn't mean we should remove the current behavior though, I more feel like this would be an option one might choose for specific libraries or Accio could even figure out itself, which libraries this approach should be applied to.

**Comment by fredpi** [comment]
Closing this, as [Accio is now deprecated](https://github.com/JamitLabs/Accio/pull/92).
