### ISSUE TITLE
Add Firebase SDKs to AccioSupport

### ISSUE THREAD

**Issue by mrylmz** [JamitLabs/Accio#42]
It is really common that the firebase SDKs are used inside iOS Projects to improve the migration experience we could add Accio support for every Firebase Project targeting iOS.

**Comment by Jeehut** [comment]
@mrylmz Sounds reasonable. Feel free to fork them to `AccioSupport` and post a PR with a text similar to [this](https://github.com/CosmicMind/Material/pull/1212) once they support Accio. You may also add them to the integration tests in the Demo project if you want, but that's optional.

**Comment by fredpi** [comment]
Closing this, as [Accio is now deprecated](https://github.com/JamitLabs/Accio/pull/92).
