### ISSUE TITLE
Performance improvments on re-runs without updates

### ISSUE THREAD

**Issue by Jeehut** [JamitLabs/Accio#43]
Currently, when the "install" command is run for a second time, all dependency resolution and framework copying is redone and takes quite some time. Instead, we could save a hash of the Package.resolved to the cache with a file named after the hash (e.g. abcd.json) which could contain the hashes of all the .framework and .dsym files required, including the commit hash and framework name (info needed for the cache lookup). 

Now when the hash file already exists, we could simply check if the existing .framework and .dsym files in the folder already have the correct hash and skip any copying steps (this can also improve performance of the update command). Also since the hash file exists, we can completely skip the dependency resolution if all dependencies are already cached (only useful for the install command).

This should be implemented after performance tests are written with some example project for the following situations:
- run "install", then re-run "install"
- run "update", then re-run "update"
- run "update", change one libraries version requirement, then re-run "update"

All three cases should have performance improvements. The last example is expected to have only small performance improvements while the first two cases should be nearly twice as fast.

**Comment by fredpi** [comment]
@Jeehut This can be closed, as you implemented it in #60, right?

**Comment by Jeehut** [comment]
Yes, I think so. I don't remember the details of #60 exactly, but it reads like it implements this. Let's close this for now and reopen in case we're proved wrong. 🎉
