### ISSUE TITLE
Implement a way of passing additional configuration to Accio

### ISSUE THREAD

**Issue by acecilia** [JamitLabs/Accio#54]
I made this issue to discuss the possibility and implementation of a way of passing additional configuration to Accio, when such configuration does not fit in the `Package.swift` file.

There has been already some discussions about this [here](https://github.com/JamitLabs/Accio/issues/48#issuecomment-495659568) and [here](https://github.com/JamitLabs/Accio/pull/50#issuecomment-494890942)

**Comment by Jeehut** [comment]
I don't mean this to be a final decision, but [here](https://github.com/JamitLabs/Accio/issues/5#issuecomment-479810415) I suggested using comments within the Package.swift file itself following the style of the Package manifest format. This also should come with a pitch on the Swift forums if it makes any sense to also introduce the same functionality to SwiftPM so we could simply uncomment the code sometime and it would continue to build.

Having that said, if the feature was too Accio-specific and unlikely to be added to SwiftPM, we could also at some point start to add a second file with an Accio-specific configuration format. But I'm not sure how this would look like. We could either use something very similar to Package.swift (maybe naming it `Accio.swift`?) or we could opt for a real configuration language (like TOML or YAML) and use that (e.g. `.accio.toml`). In any case, I'd rather prevent this solution if possible. I'd only opt for it if it was clear that the approach of extending the Package.swift file with comments would become too cumbersome as we need to add too many such changes over time (and yes, they definitely are somehow 'hacky').

**Comment by fredpi** [comment]
Closing this, as [Accio is now deprecated](https://github.com/JamitLabs/Accio/pull/92).
