### ISSUE TITLE
Error: The file “Info.plist” couldn’t be opened

### ISSUE THREAD

**Issue by phimage** [JamitLabs/Accio#73]
I have an issue with #69, #70
in added `verifyBundleVersion` function
I have `plistURL` value "file:///XXXX/Dependencies/macOS/Result.framework/Info.plist"
and there is no "Info.plist" at all here so reading the file launch an error

I have one into  "file:///XXXX/Dependencies/macOS/Result.framework/Versions/A/Resources/Info.plist"

only have symbolic link and Versions
```swift
Headers -> Versions/Current/Headers
Modules -> Versions/Current/Modules
Resources -> Versions/Current/Resources
Result -> Versions/Current/Result
```

The framework has been build using carthage 0.33.0 as I see in the log after removing accio cache

_I use Xcode 10.3 so maybe something change, because I have old carthage build by me with command line, with an Info.plist at framework root folder_

So to reproduce accio cache must be removed

Maybe it is a carthage issue if the Info.plist must be at root, but if not mandatory this is an accio issue

**Comment by Jeehut** [comment]
@mrylmz Do you know more about this? Sounds like it has to do with something we talked about recently ...

**Comment by mrylmz** [comment]
Making the Bundle verification optional could be a short term solution here, the carthage builds should always include the correct bundle version for deployment. For a reasonable stable solution we should investigate some time in inspecting the framework specification from apple.
