### ISSUE TITLE
Error installing Accio

### ISSUE THREAD

**Issue by pvcary** [JamitLabs/Accio#83]
Hi there, I'm having an issue installing Accio. I'm getting this Validation Failed error after the brew install accio command:

"The listed users and repositories cannot be searched either because the resources do not exist or you do not have permission to view them."

 My homebrew version is current at 2.1.15. Please see the screenshot below:

<img width="1680" alt="Screen Shot 2019-11-01 at 1 58 14 PM" src="https://user-images.githubusercontent.com/13153202/68049075-ffa52480-fcaf-11e9-9f7f-248949112b1c.png">

Thanks in advance!

**Comment by Jeehut** [comment]
@pvcary Thanks for reporting this. Can you please provide more info about:

1. the version of macOS you are using
2. the version of yourXcode command line tools (`xcodebuild -version`)
3. the version of Swift (`swift -version`)

Thet would help fix the issue.

**Comment by fredpi** [comment]
@pvcary I'm closing this as there are no other reports of this issue and without further information I don't have any idea how to fix this. Feel free to open this again if this issue still persists for you and if you can provide more information on the versions you're using ;)
