### ISSUE TITLE
Pick a less generic name than `Dependencies` for your folder

### ISSUE THREAD

**Issue by LucasVanDongen** [JamitLabs/Accio#84]
We've spent some time figuring out why my teammates didn't get the files that were in my `Dependencies` folder. Apparently the default `.gitignore` here on GitHub now has a specific entry for Accio which prevents anyone else from using a folder named `Dependencies` anywhere since it's now ignored. I am probably not the first person running into this.

As I'm not even a user of your tool I was totally not expecting this, other tools have unique names for the folders that could/should go into `.gitignore` like `Pods`, `Carthage` etcetera. I would like to propose that you rename the default folder name to something unique like `Accio`.

**Comment by fredpi** [comment]
@LucasVanDongen Thanks for the suggestion – it sounds reasonable to change the folder name, but I'm thinking how we can do it without breaking apps that are already running Accio. Maybe still looking up the `Dependencies` folder as a fallback...

What do you think, @Jeehut?

**Comment by Jeehut** [comment]
Sounds reasonable, but this change is breaking as people might have workflows (e.g. on CIs) that expect the files to be in the current directory, so it should only be included in a new major release.

**Comment by acecilia** [comment]
What about introducing an option to change the default `Dependencies` folder name to a custom one? Then you could release such change anytime

**Comment by fredpi** [comment]
@acecilia As a sidenote: Your configuration branch isn't merged yet, but as far as I can see, there's also no PR open (https://github.com/JamitLabs/Accio/pull/74 didn't merge into `stable`). What's the current status there?

Apart from that, I'm still in favor of not making this a configurable option as I don't see any issues with just changing the default to `AccioDependencies` while still looking up `Dependencies` if `AccioDependencies` is nowhere to be found. Why do you think this is an issue, @Jeehut?

**Comment by Jeehut** [comment]
As I wrote in [my comment above](https://github.com/JamitLabs/Accio/issues/84#issuecomment-573533037), I just think we should include it in a new major release. I'm not against the renaming by any means. Actually, I plan to do a new major release for https://github.com/JamitLabs/Accio/issues/81 anyways, so we could just merge into `stable` and and wait until 1.0 is prepared with that feature (and some more like https://github.com/JamitLabs/Accio/issues/14). Until then, early-birds can just install from the `stable` branch.

**Comment by fredpi** [comment]
@Jeehut Considering that we may want to release minor fixes in the meantime, I would prefer not to merge this into `stable` until just before the new major release. I can create a PR that doesn't get merged until then – what about that?

**Comment by Jeehut** [comment]
Okay, agreed, makes sense. But let's create a `release/1.0.0` branch instead, I would suggest and merge all changes related to the next major release there. We just need to make sure to rebase that branch regularly when we make changes to the `stable` in the meantime.

**Comment by acecilia** [comment]
@fredpi about the configuration branch, I did not continue working into it. So far we did not end up using Accio in my company, and I could not find time on my own to progress on it :/

**Comment by fredpi** [comment]
Closing this, as [Accio is now deprecated](https://github.com/JamitLabs/Accio/pull/92).
