### ISSUE TITLE
Support shorthand Semantic Version Strings

### ISSUE THREAD

**Issue by jaerod95** [JamitLabs/Accio#86]
If a project that supports Swift Package Manager doesn't tag their releases using valid semantic versioning (major.minor.patch) then Accio can't find the tags and throws the following error:

```
error: the package dependency graph could not be resolved; unable to find any available tag for the following requirements:
    https://github.com/username/PackageName.git @ 1.3.0..<2.0.0 (or other version ranges)
```
An example was the library [ThirdPartyMailer](https://github.com/jaerod95/ThirdPartyMailer) which uses only major and minor versions.

Can we add support for parsing versions that might be missing a patch or minor version?

**Comment by Jeehut** [comment]
Thank you for reporting this issue. I'm not sure if we can fix it so easily, the only ways I can come up with are really weird workarounds. We'd probably need to fix this in SwiftPM directly. Or do you have any idea how we could fix this in Accio easily?

As a workaround, you might want to opt for specifying a branch or a specific commit hash instead.

**Comment by fredpi** [comment]
Closing this, as [Accio is now deprecated](https://github.com/JamitLabs/Accio/pull/92).
